### ISSUE TITLE
인증 이슈 예시

### ISSUE THREAD

**Issue by indigopyj** [indigopyj/StudyWithGrrr#2]
### 김땡땡 todo list

- [ ] 공부하기
- [ ] 밥 먹기
- [ ] 자기

**Comment by indigopyj** [comment]
## 9/20 ~ 9/27 인증

<img src="https://user-images.githubusercontent.com/17904547/95465319-f17a8080-09b5-11eb-9fe8-870adc8c972a.png" width="500">
공부 인증

**Comment by gityunjae** [comment]
- [ ] 이렇게 추가 가능?
